sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123123
  redis:
    host: localhost
    port: 6379
    password: 123123
    database: 10
  wechat:
    appid: wxf0f4f90fc540bc88
    secret: c76af0f3e0aed5bc5c8e940d0167af64

